spring:
    data:
      mongodb:
            uri: 192.168.100.130:27017
            database: lgb
            repositories:
              enabled: true
            authenticationDatabase: admin
      neo4j:
            username: neo4j
            password: 123456
            uri: http://192.168.100.130:7474
      redis:
            database: 0
            host: 192.168.100.130
            port: 6379
            timeout: 600000
            pool:
              max-active: 20
              max-wait: -1
              max-idle: 2
              min-idle: 0
    mvc:
         view:
            prefix: /view/
            suffix: .jsp
#kafka
# 指定kafka 代理地址，可以多个
    kafka:
      bootstrap-servers: 192.168.100.130:9092
      consumer:
# 指定默认消费者group id
        group-id: event_new
      template:
# 指定默认topic id
        default-topic: event_new
      listener:
# 指定listener 容器中的线程数，用于提高并发量
        concurrency: 10
      producer:
# 每次批量发送消息的数量
        batch-size: 1000

